SIAT/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/reglas/datos', 'DataTableController@getReglas')->name('datatable.reglas');
Route::get('/areas/datos', 'DataTableController@getAreas')->name('datatable.areas');
Route::get('/usuarios/datos', 'DataTableController@getUsuarios')->name('datatable.usuarios');
Route::get('/roles/datos', 'DataTableController@getRoles')->name('datatable.roles');
Route::get('/profesionales/datos', 'DataTableController@getProfesionales')->name('datatable.profesionales');
Route::get('/proyectos/datos', 'DataTableController@getProyectos')->name('datatable.proyectos');
Route::get('/proyectos/datosAsignacion', 'DataTableController@getProyectosAsignacion')->name('datatable.proyectosAsignacion');
Route::get('/proyectos/{id}/profesionales/datosAsignacion', 'DataTableController@getTribunales')->name('datatable.tribunales');
Route::get('/proyectos/datosAsignados', 'DataTableController@getProyectosAsignados')->name('datatable.proyectosAsignados');
Route::get('/proyectos/{id}/profesionales', 'DataTableController@getTribunalesAsignados')->name('datatable.proyectoTribunales');
Route::get('/profesionales/proyectosAsignados', 'DataTableController@getProyectosProfesional')->name('datatable.proyectosAsignadosProfesional');
Route::get('/profesionales/competencias', 'DataTableController@getCompetencias')->name('datatable.competencia');
Route::get('/profesionales/intereses', 'DataTableController@getIntereses')->name('datatable.interes');

Route::get('/rol/index', 'RolController@index')->name('rol.index');
Route::get('/rol/crear', 'RolController@create')->name('rol.create');
Route::post('/rol/guardar', 'RolController@store')->name('rol.store');
Route::get('/rol/ver/{id}', 'RolController@show')->name('rol.show');
Route::get('/rol/editar/{id}', 'RolController@edit')->name('rol.edit');
Route::put('/rol/editar/update/{id}', 'RolController@update')->name('rol.update');
Route::delete('/rol/eliminar/{id}', 'RolController@destroy')->name('rol.destroy');

Route::get('/usuario/index', 'UserController@index')->name('usuario.index');
Route::get('/usuario/ver/{id}', 'UserController@show')->name('usuario.show');
Route::get('/usuario/editar/{id}', 'UserController@editarUser')->name('usuario.edit');
Route::put('/usuario/editar/update/{id}', 'UserController@update')->name('usuario.update');

Route::get('/usuario/crear', 'UserController@crearUser')->name('usuario.create');
Route::post('/usuario/guardar', 'UserController@store')->name('usuario.store');
Route::delete('/usuario/eliminar/{id}', 'UserController@eliminarUser')->name('usuario.destroy');

Route::post('/areas/importar', 'ExcelController@importarAreas');
Route::post('/profesionales/importar', 'ExcelController@importarProfesionales');
Route::post('/proyectos/importar', 'ExcelController@importarProyectos');

Route::get('/areas/{id}/editar/subareas/crear', 'AreaController@createSubarea')->name('subareas.create');
Route::post('/areas/{id}/editar/subareas/guardar', 'AreaController@storeSubarea')->name('subareas.store');
Route::get('/areas/{id}/editar/subareas/{idSub}/editar', 'AreaController@editSubarea')->name('subareas.edit');
Route::put('/areas/{id}/editar/subareas/{idSub}', 'AreaController@updateSubarea')->name('subareas.update');
Route::delete('/areas/{id}/editar/subareas/{idSub}', 'AreaController@destroySubarea')->name('subareas.destroy');
/*COMPETENCIAS Y INTERES*/
Route::get('/competencias', 'UserController@competenciasMostrar');
Route::get('are/{id}', 'UserController@getArea');
Route::post('guardar', 'UserController@competenciasGuardar')->name('guardar.competencias');

Route::get('/interes', 'UserController@interesMostrar');
Route::post('guardarinteres', 'UserController@interesGuardar')->name('guardar.interes');
/*USER*/
Route::get('/User/password', 'UserController@password');
Route::post('/User/updatepassword', 'UserController@updatePassword');
Route::get('/secretaria/perfil','UserController@getProfileSecretaria')->name('secretaria.perfil');
Route::put('/secretaria/perfil/update/','UserController@updateProfileSecretaria')->name('secretaria.perfil.update');
Route::post('/secretaria/update/foto','UserController@updateFotoSecretaria')->name('secretaria.update.foto');


Route::get('/admin/perfil','UserController@getProfileAdministrador')->name('admin.perfil');
Route::put('/admin/perfil/update/','UserController@updateProfileAdministrador')->name('admin.perfil.update');
Route::post('/admin/update/foto','UserController@updateFotoAdministrador')->name('admin.update.foto');

Route::get('consejero/perfil','UserController@getProfileConsejero')->name('consejero.perfil');
Route::put('/consejero/perfil/update','UserController@updateProfileConsejero')->name('consejero.perfil.update');
Route::post('/consejero/update/foto','UserController@updateFotoConsejero')->name('consejero.update.foto');

Route::get('/perfil','ProfesionalController@showProfesional')->name('perfil.show');
Route::put('/perfil/{id}','ProfesionalController@updateProfesional')->name('perfil.update');
Route::post('/perfil/update/foto','ProfesionalController@updateFotoProfesional')->name('perfil.update.foto');
Route::get('/profesional/proyecto', 'ProfesionalController@getProyectos')->name('profesional.proyecto');

Route::get('/asignaciones', 'AsignacionController@index')->name('asignacion.index');
Route::get('/asignaciones/{id}/asignar', 'AsignacionController@asignarTribunales')->name('asignaciones.asignar');
Route::get('/asignaciones/{id}/profesionales/{idProfesional}/reasignar', 'AsignacionController@reasignarTribunal')->name('asignaciones.reasignar');
Route::get('/asignaciones/{id}/tribunales', 'AsignacionController@getTribunales')->name('asignaciones.tribunales');
Route::get('/asignaciones/{id}/estado', 'AsignacionController@ProyectoDefendido')->name('asignaciones.defendido');
Route::get('/asignaciones/proyectosAsignados', 'AsignacionController@getProyectosAsignados')->name('asignaciones.asignados');
Route::post('/asignaciones/{id}/notificar', 'AsignacionController@notificarTribunales')->name('asignaciones.notificar');
Route::post('/asignaciones/{id}/profesionales/{idProfesional}/notificarReasignacion', 'AsignacionController@notificarTribunalReasignado')->name('asignaciones.notificarReasignacion');

Route::resources([
    'reglas' => 'ReglaController',
    'areas' => 'AreaController',
    'profesionales' => 'ProfesionalController',
    'proyectos' => 'ProyectoController'
]);

SIAT/app/Regla.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Regla extends Model

{ 
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
   

   

    protected $table = 'regla'; 

    protected $primaryKey = 'id_reg';

    protected $fillable =[
    	'des_reg',
    	'val_reg'
    ];

    protected $guarded =[

    ];

}

SIAT/app/Http/Controllers/ReglaController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Regla;
use Illuminate\Support\Facades\Redirect;
use App\Http\Requests\ReglasFormRequest;
use App\Http\Requests\EditarReglasRequest;
use Laracasts\Flash\Flash;
use Auth;
class ReglaController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:Administrador|Consejero');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $request->user()->authorizeRoles(['Administrador', 'Consejero']);
        return view('regla.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */    
    public function create()
    {
        return view('regla.crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */   
    public function store(ReglasFormRequest $request){

        
        $reg = \DB::table('regla')->select()->where('des_reg','=',$request->des_reg)->get();
        
           $rules = [
            'des_reg'     => 'required',
            'val_reg'  => 'required'
            ];
        
        try {
            // Ejecutamos el validador y en caso de que falle devolvemos la respuesta
            $validator = \Validator::make($request->all(), $rules);
            if ($validator->fails()) {
                return [
                    'created' => false,
                    'errors'  => $validator->errors()->all()
                ];
            }
            if (empty($reg->first())){
                $regla = $request->all();
                $regla = Regla::create($regla);
                $regla->save();
                Flash('Se ha creado una nueva regla.')->success();
                return redirect('/reglas');   
            }
            Flash::error("Error no se puede guardar, la regla ya existe.");
            return view('regla.crear');
        } catch (Exception $e) {
            \Log::info('Error creating role: '.$e);
            return \Response::json(['created' => false], 500);
        }
        


    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */    
    public function show($id)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $regla = Regla::find($id);
        return view('regla.editar')-> with('regla', $regla);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EditarReglasRequest $request, $id)
    {
        
        $regla = Regla::find($id);
        $regla-> fill($request->all());
        $regla-> save();
        Flash('Se ha modificado la regla correctamente.')->success();
        return redirect()->route('reglas.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        \DB::table('regla')->select()->where('id_reg',$id)->delete();
        Flash('Se ha eliminado una regla correctamente.')->success();
        return back();
    }
}

SIAT/resources/views/Regla/crear.blade.php
@extends('master')
@section('title', 'Nueva Regla')
@section('content')
@extends('cabecera-con-sesion-usuario')  
            <div class="card miCard marginDivUp">
                <div class="card-body">
                     <h3 class = "titCard" align="center">Nueva Regla</h3>
                     @include('flash::message')
                     <div>
                        <form class="needs-validation" novalidate action="{{ route('reglas.store') }}" method ="POST" enctype="multipart/form-data">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                            
                            <div class="form-group estiloCard">
                                <input name="des_reg" type="text" class="form-control" placeholder="Descripción" value = "{{old('des_reg')}}" maxlength="100" pattern="^([A-ZÁÉÍÓÚa-zñáéíóúäëïöü]+[\s]*)+$" title="Introduzca una descripcion entre 5 y 100 letras" minlength="5" required>

                                <div class="invalid-feedback">
                                    Introduzca una descripción entre 5 y 100 letras
                                </div>
                            </div>
                            <div class="form-row align-items-center estiloCard">
                                <div class="col-md-3 my-1">
                                    <label for="label" class = "card-text  mr-sm-2"> Valor </label>
                                </div>
                                <div class="col-md-9 my-1">
                                    <input name="val_reg" type="number" class="form-control" value = "{{old('val_reg')}}" maxlength="100" title="Introduzca un numéro" minlength="5" required>
                                    <div class="invalid-feedback">
                                        Introduzca un valor numérico
                                    </div>
                                </div>   
                            </div>
                            <div class="estiloCard">
                                <button class="btn btn-default" type="reset" onclick="history.back()">Cancelar</button>
              
                                <button id="guardar" class="btn btnColor btnCard" type="submit" data-toggle="modal" data-target="#mensaje" value ="1">Guardar</button>

                                 
                            </div>
                        </form>
                    </div>
                </div> 
            </div>
            <br>
@endsection
           

SIAT/resources/views/Regla/editar.blade.php
@extends('master')
@section('title', 'Editar Regla')
@section('content')
@extends('cabecera-con-sesion-usuario')
<br>
        
        <br>
            <div class="card miCard marginDivUp">
                <h3 class = "titCard" align="center">Editar Regla</h3>
                <div class="card-body">
                     <h3 class = "titCard" align="left"></h3>

                        <form class="needs-validation" novalidate action="{{ route('reglas.update',$regla->id_reg)}}" method="POST" enctype="multipart/form-data">
                            <input type="hidden" name="_method" value="PUT">
                                    {{ csrf_field() }}
                                                
                            <div class="form-group estiloCard">
                                
                                <input class="form-control" placeholder="Descripcion"  name="des_reg" type="text"  id="des_reg"  value="{{ $regla->des_reg }}" maxlength="100" pattern="^([A-ZÁÉÍÓÚa-zñáéíóúäëïöü]+[\s]*)+$" title="Introduzca una descripcion entre 5 y 100 letras" minlength="5" required>
                                <div class="invalid-feedback">
                                    Introduzca una descripción entre 5 y 100 letras
                                </div>
                            </div>
                            <div class="form-row align-items-center estiloCard">
                                <div class="col-md-3 my-1">
                                    <label for="label" class = "card-text  mr-sm-2"> Valor </label>
                                </div>
                                <div class="col-md-9 my-1">
                                    <input id="val_reg" name="val_reg" type="number" class="form-control"  value = "{{ $regla->val_reg }}" maxlength="100"  title="Introduzca un numero" minlength="5" required>
                                    <div class="invalid-feedback">
                                        Introduzca un valor numérico
                                    </div>
                                </div>   
                            </div>

                            <div class="estiloCard">
                                
                                <button class="btn btn-default" type="reset" onclick="history.back()">Cancelar</button>
              
                                <button type="submit" class="btn btnColor btnCard">Guardar Cambios</button>

                            </div>
                        </form>
                     </div>
                    
                </div>
            

@endsection
           

SIAT/resources/views/Regla/index.blade.php
@extends('master')
@section('title', 'Reglas')
@section('content')

@extends('cabecera-con-sesion-usuario')

	

<!-- Image and text -->
<h2  class="title">REGLAS</h2>
	<div class="container">
		@include('flash::message')
		<div class="containerTable">
		<table id="tablaRegla" class="table table-bordered table-hover">
		  <thead class="headTableColor">
				<tr class="titleSinNegrilla">
					<th scope="col" >N°</th>
					<th scope="col" style="width: 500px;">Descripción</th>
					<th scope="col">Valor</th>
					<th>Acción</th>
				</tr>
		  </thead>
		</table>
		</div>
		<br>
		<div class="btnFormat">
			<div class="row" style="text-align: center">
				<div class="col-md-2"><button type="button" onclick="history.back(-1)" " class="btn btn-primary changeColorBtn btnColor">Atrás</button></div>
				<div class="col-md-2"></div>
				<div class="col-md-2"></div>
				<div class="col-md-2"></div>
				<div class="col-md-2"></div>
				<div class="col-md-2"><a href="{{route('reglas.create')}}" class="btn btn-primary changeColorBtn btnColor">nueva regla</a></div>
			</div>
		</div>		
	</div>
@endsection
@section('scripts')
	<script type="text/javascript">
		  $(document).ready(function() {
		  $('#tablaRegla').DataTable({
		      processing: true,
		      serverSide: true,
		     ajax: "/TIS-SATPFG/SIAT/public/reglas/datos",
		     ajax: "{{route('datatable.reglas')}}",
		      columns: [
		          { data: 'id_reg', name: 'id_reg' },
		          { data: 'des_reg', name: 'des_reg', width: '60%' },
		          { data: 'val_reg', name: 'val_reg' },
		          { data: 'action', name: 'action', orderable: false, searchable: false}
		      ],
		      language: esp
		  });
		});
	</script>
@endsection